### ISSUE TITLE
Add `get_channel_dtype` and `get_channel_shape` methods

### ISSUE THREAD

**Issue by Illviljan** [ratal/mdfr#14]
I would like to see the methods `get_channel_dtype` and `get_channel_shape` added to the api to avoid loading all the data to memory.

To be clear, they would correspond to:
```python
import numpy as np

arr = np.array([3,6,8], dtype=float)
arr.shape
Out[33]: (3,)
arr.dtype
Out[34]: dtype('float64')
```

This allows you to reason about the arrays without loading the data with for example [dask](https://www.dask.org/).

**Comment by ratal** [comment]
You can have a look at arrow-rs-instead-of-arrow2 branch, it contains a new method .get_channel_dtype(), returning a struct with fields kind and shape

**Comment by ratal** [comment]
latest release should fix this issue

**Comment by Illviljan** [comment]
Cool, thanks!
