### ISSUE TITLE
obj = mdfr.Mdf('path/to/file.mdf') error

### ISSUE THREAD

**Issue by sharkyangliu11** [ratal/mdfr#5]
It shows AttributeError: module 'mdfr' has no attribute 'Mdf' error

**Comment by ratal** [comment]
I do not see any reason to have this error from mdfr. Are you sure you are not mixing up with mdfreader ? what is telling your autocompletion from iPython ?
How did you install mdfr ? via pip or compiled ?

**Comment by sharkyangliu11** [comment]
I installed it using pip. import mdfr is fine. but it will get error for the obj = mdfr.Mdf('test_basic.mf4').  It shows AttributeError: module 'mdfr' has no attribute 'Mdf'

**Comment by ratal** [comment]
Maybe stupid point, you could try with obj = mdfr.Mdf**r**('test_basic.mf4') the 'r' was missing.
Autocompletion with ipython should have told you.
Anyway, I cannot reproduce your issue on several platforms. Is still a concern for you ?
