### ISSUE TITLE
Cannot install using pip 

### ISSUE THREAD

**Issue by jijosg** [ratal/mdfr#6]
I am unable to install this library using pip. Are there any pre-requisites to install?

```bash
ERROR: Could not find a version that satisfies the requirement mdfr (from versions: none)
ERROR: No matching distribution found for mdfr
```

**Comment by ratal** [comment]
On what platform are you trying to install it ? What python version ?
I think currently packages are automatically generated up to python 3.10 and for win x64, macosX, linux, etc. For more detailed list: [list](https://pypi.org/project/mdfr/#files)
You could also try to build it for your own environment, installing Rust and maturin, but not so straight forward probably.

**Comment by ratal** [comment]
I pushed new version 4.1 which includes python 3.1 as it more wide spread since last year + many other dependencies updates. Maybe you can give try.
